blackshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('product/', include('product.urls')),
    path('contact/', include('contact.urls')),
    path('account/', include('account.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

app_name = 'product'


urlpatterns = [
    path('',views.product, name = "product"),
    path('single-page/<slug:slug>',views.single, name='single')
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index')
]

product/models.py
from django.db import models
 

class ProductCategory(models.Model):
    title = models.CharField(max_length=64)
    def __str__(self):
        return self.title 

class Product(models.Model):
    title = models.CharField(max_length = 300)
    is_actie = models.BooleanField(default=False)
    is_delete = models.BooleanField(default=False)
    short_description = models.CharField(max_length = 260)
    description = models.TextField()
    category = models.ManyToManyField(ProductCategory)
    price = models.IntegerField()
    slug = models.SlugField()
    picture = models.ImageField(upload_to="product" ,null= True, blank=True)

product/views.py
from django.shortcuts import render
from . import models
from .models import Product

# Create your views here.
def product(request):
    products= Product.objects.all()
    return render(request,'product/main.html',{'products':products})

def single(request,slug):
    product = Product.objects.get(slug=slug)
    
    return render(request,'product/single.html',{'product':product})

product/templates/product/index.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
{%  for p in products  %}
    <h1>{{p.title}}</h1>



    <div class="item">
        <div class="product-card">
            <div class="product-head">
                <div class="rating-stars">
                    <i class="mdi mdi-star active"></i>
                    <i class="mdi mdi-star active"></i>
                    <i class="mdi mdi-star active"></i>
                    <i class="mdi mdi-star active"></i>
                    <i class="mdi mdi-star active"></i>
                </div>
            </div>
            <a class="product-thumb" href="shop-single.html">
                {% if p.picture %}
                <img width="100" src="{{ p.picture.url }}" alt="Product Thumbnail">
                {% endif %}
            </a>
            <div class="product-card-body">
                <h5 class="product-title">
                    <a href="shop-single.html">{{p.title}}</a>
                </h5>
                <a class="product-meta" href="shop-categories.html">لباس زنانه</a>
                <span class="product-price">157,000 تومان</span>
            </div>
        </div>
    </div>
{%endfor%}    
{% endblock %}

product/templates/product/main.html
{% extends 'shared/base.html' %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


{% block content %}

{% for p in products   %}
        <main class="main-content dt-sl mb-3">
            <div class="container main-container">
                <!-- Start Main-Slider -->
                <div class="row mb-3">
                                <!-- Start Product-Slider -->
                                <div class="col-12 px-res-0">
                                    <div class="product-carousel carousel-md owl-carousel owl-theme">
                                        <div class="item">
                                            <div class="product-card">
                                                <div class="product-head">
                                                    <div class="rating-stars">
                                                        <i class="mdi mdi-star active"></i>
                                                        <i class="mdi mdi-star active"></i>
                                                        <i class="mdi mdi-star active"></i>
                                                        <i class="mdi mdi-star active"></i>
                                                        <i class="mdi mdi-star active"></i>
                                                    </div>
                                                    <div class="discount">
                                                        <span>20%</span>
                                                    </div>
                                                </div>
                                                <a class="product-thumb" href="{% url 'product:single' slug=p.slug %}">
                                                    <img src="{{ p.picture.url }}" alt="Product Thumbnail">
                                                </a>
                                                <div class="product-card-body">
                                                    <h5 class="product-title">
                                                        <a href="shop-single.html">{{p.title}}</a>
                                                    </h5>
                                                    <h5>{{p.short_description}}</h5>
                                                    <span class="product-price">{{p.price}}</span>
                                                </div>
                                            </div>
                                        </div>
                                    
                                <!-- End Product-Slider -->

                            </div>

                    </div>
                        </div>
                    </div>
                </div>

{% endfor   %}
{%endblock content%}