account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_page, name='login_page'),
    path('activate-account/<str:activate_code>', views.activate_account),
    path('logout/', views.logout_page, name='logout_page')
]

blackshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('product/', include('product.urls')),
    path('contact/', include('contact.urls')),
    path('account/', include('account.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index')
]

templates/login.html
{% load static    %}



<!DOCTYPE html>
<html lang="fa">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="theme-color" content="#f7858d">
    <meta name="msapplication-navbutton-color" content="#f7858d">
    <meta name="apple-mobile-web-app-status-bar-style" content="#f7858d">
    <title>didikala | Login Page</title>
    <!-- Font Icon -->
    <link rel="stylesheet" href="/static/css/vendor/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/vendor/materialdesignicons.min.css">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="/static/css/vendor/bootstrap.min.css">
    <!-- Plugins -->
    <link rel="stylesheet" href="/static/css/vendor/bootstrap-slider.min.css">
    <link rel="stylesheet" href="/static/css/vendor/owl.carousel.min.css">
    <link rel="stylesheet" href="/static/css/vendor/jquery.horizontalmenu.css">
    <link rel="stylesheet" href="/static/css/vendor/fancybox.min.css">
    <link rel="stylesheet" href="/static/css/vendor/nice-select.css">
    <link rel="stylesheet" href="/static/css/vendor/nouislider.min.css">
    <!-- Main CSS File -->
    <link rel="stylesheet" href="/static/css/main.css">
    <link rel="stylesheet" href="/static/css/colors/default.css" id="colorswitch">
</head>

<body>
    <div class="wrapper">
        <!-- Start main-content -->


        <main class="main-content dt-sl mt-4 mb-3">
            <div class="container main-container">
                <div class="row">
                    <div class="col-xl-4 col-lg-5 col-md-7 col-12 mx-auto">
                        <div class="logo-area text-center mb-3">
                            <a href="#"><img src="/static/img/logo.png" class="img-fluid" alt="logo"></a>
                        </div>
                        <div class="auth-wrapper form-ui border pt-4">
                            <div class="section-title title-wide mb-1 no-after-title-wide">
                                <h2 class="font-weight-bold">ورود</h2>
                            </div>
                            <div>
                            </div>
                            <form action="{% url 'account:login_page' %}" method="post">
                                {% csrf_token %}
                                <div class="form-row-title">
                                    <h3>{{ form.email.label }}</h3>
                                </div>
                                <div class="form-row with-icon">
                                    {{ form.email }}
                                    <i class="mdi mdi-account-circle-outline"></i>
                                </div>
                                <div class="form-row-title">
                                    <h3>رمز عبور</h3>
                                </div>
                                <div class="form-row with-icon">
                                   {{ form.password}}
                                    <i class="mdi mdi-lock-open-variant-outline"></i>
                                </div>
                                {{form.email.errors}}
                                <div class="form-row mt-2">
                                    <div class="custom-control custom-checkbox float-right mt-2">
                                        <input type="checkbox" class="custom-control-input" id="customCheck3">
                                        <label class="custom-control-label" for="customCheck3">
                                            مرا به خاطر بسپار
                                        </label>
                                    </div>
                                </div>
                                <div class="form-row mt-3">
                                    <a href="#"><button class="btn-primary-cm btn-with-icon mx-auto w-100 " type="submit">
                                        ورود به دیدیکالا
                                    </button>
                                   </a> 
                                </div>
                            </form>
                            <div class="form-footer mt-3">
                                <div>
                                    <span class="font-weight-bold">کاربر جدید هستید؟</span>
                                    <a href="#" class="mr-3 mt-2">ثبت نام در دیدیکالا</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <!-- End main-content -->
        <!-- Start mini-footer -->
        <footer class="mini-footer dt-sl">
            <div class="container main-container">
                <div class="row">
                    <div class="col-12">
                        <ul class="mini-footer-menu">
                            <li><a href="#">درباره دیدیکالا</a></li>
                            <li><a href="#">فرصت های شغلی</a></li>
                            <li><a href="#">تماس با ما</a></li>
                            <li><a href="#">همکاری با سازمان ها</a></li>
                        </ul>
                    </div>
                    <div class="col-12 mt-2 mb-3">
                        <div class="footer-light-text">
                            استفاده از مطالب فروشگاه اینترنتی دیدیکالا فقط برای مقاصد غیرتجاری و با ذکر منبع بلامانع
                            است. کلیه حقوق این سایت متعلق به (فروشگاه آنلاین دیدیکالا) می‌باشد.
                        </div>
                    </div>
                    <div class="col-12 text-center">
                        <div class="copy-right-mini-footer">
                            Copyright © 2019 Didikala
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- End mini-footer -->
    </div>
    <!-- colorPanel -->
    <div id="colorswitch-option">
        <button><i class="mdi mdi-settings"></i></button>
        <ul>
            <li class="active" data-path="/static/css/colors/default.css"><span
                    style="background-color: #f7858d;"></span></li>
            <li data-path="/static/css/colors/amber-color.css"><span style="background-color: #ffab00;"></span></li>
            <li data-path="/static/css/colors/blue-color.css"><span style="background-color: #2979ff;"></span></li>
            <li data-path="/static/css/colors/blue-grey-color.css"><span style="background-color: #607d8b;"></span>
            </li>
            <li data-path="/static/css/colors/brown-color.css"><span style="background-color: #795548;"></span></li>
            <li data-path="/static/css/colors/cyan-color.css"><span style="background-color: #00bcd4;"></span></li>
            <li data-path="/static/css/colors/green-color.css"><span style="background-color: #4caf50;"></span></li>
            <li data-path="/static/css/colors/indigo-color.css"><span style="background-color: #3f51b5;"></span></li>
            <li data-path="/static/css/colors/lime-color.css"><span style="background-color: #cddc39;"></span></li>
            <li data-path="/static/css/colors/orange-color.css"><span style="background-color: #ff9800;"></span></li>
            <li data-path="/static/css/colors/red-color.css"><span style="background-color: #f44336;"></span></li>
            <li data-path="/static/css/colors/teal-color.css"><span style="background-color: #009688;"></span></li>
            <li data-path="/static/css/colors/purple-color.css"><span style="background-color: #9c27b0;"></span></li>
        </ul>
    </div>
    <!-- end colorPanel -->
    <!-- Core JS Files -->
    <script src="/static/js/vendor/jquery-3.4.1.min.js"></script>
    <script src="/static/js/vendor/popper.min.js"></script>
    <script src="/static/js/vendor/bootstrap.min.js"></script>
    <!-- Plugins -->
    <script src="/static/js/vendor/bootstrap-slider.min.js"></script>
    <script src="/static/js/vendor/owl.carousel.min.js"></script>
    <script src="/static/js/vendor/owl.carousel2.thumbs.min.js"></script>
    <script src="/static/js/vendor/jquery.nicescroll.min.js"></script>
    <script src="/static/js/vendor/jquery.nice-select.min.js"></script>
    <script src="/static/js/vendor/nouislider.min.js"></script>
    <script src="/static/js/vendor/jquery.horizontalmenu.js"></script>
    <script src="/static/js/vendor/jquery.fancybox.min.js"></script>
    <script src="/static/js/vendor/countdown.min.js"></script>
    <script src="/static/js/vendor/wNumb.js"></script>
    <script src="/static/js/vendor/ResizeSensor.min.js"></script>
    <script src="/static/js/vendor/theia-sticky-sidebar.min.js"></script>
    <!-- Main JS File -->
    <script src="/static/js/main.js"></script>
</body>

</html>

templates/welcome.html
<!DOCTYPE html>
<html lang="fa">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="theme-color" content="#f7858d">
    <meta name="msapplication-navbutton-color" content="#f7858d">
    <meta name="apple-mobile-web-app-status-bar-style" content="#f7858d">
    <title>didikala | Welcome Page</title>
    <!-- Font Icon -->
    <link rel="stylesheet" href="./assets/css/vendor/font-awesome.min.css">
    <link rel="stylesheet" href="./assets/css/vendor/materialdesignicons.min.css">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="./assets/css/vendor/bootstrap.min.css">
    <!-- Plugins -->
    <link rel="stylesheet" href="./assets/css/vendor/bootstrap-slider.min.css">
    <link rel="stylesheet" href="./assets/css/vendor/owl.carousel.min.css">
    <link rel="stylesheet" href="./assets/css/vendor/jquery.horizontalmenu.css">
    <link rel="stylesheet" href="./assets/css/vendor/fancybox.min.css">
    <link rel="stylesheet" href="./assets/css/vendor/nice-select.css">
    <link rel="stylesheet" href="./assets/css/vendor/nouislider.min.css">
    <!-- Main CSS File -->
    <link rel="stylesheet" href="./assets/css/main.css">
    <link rel="stylesheet" href="./assets/css/colors/default.css" id="colorswitch">
</head>

<body>
    <div class="wrapper">
        <!-- Start main-content -->
        <main class="main-content dt-sl mt-4 mb-3">
            <div class="container main-container">
                <div class="row">
                    <div class="col-xl-4 col-lg-5 col-md-7 col-12 mx-auto">
                        <div class="logo-area text-center mb-3">
                            <a href="#"><img src="./assets/img/logo.png" class="img-fluid" alt="logo"></a>
                        </div>
                        <div class="auth-wrapper form-ui border pt-4">
                            <div class="section-title title-wide mb-1 pb-0 no-after-title-wide">
                                <h2 class="font-weight-bold">به دیدیکالا خوش آمدید</h2>
                            </div>
                            <div class="circle-box-icon">
                                <i class="mdi mdi-account-circle-outline"></i>
                            </div>
                            <h5 class="text-center font-weight-bold">حساب کاربری شما در دیدیکالا ساخته شد</h5>
                            <div class="message-light">
                                اکنون می‌توانید به صفحه‌ای که در آن بودید بازگردید و یا با تکمیل اطلاعات حساب کاربری خود
                                به کلیه امکانات و سرویس‌های تاپ کالا و سرویس‌های وابسته به آن دسترسی داشته باشید
                            </div>
                            <div class="text-center mt-5 mb-4">
                                <a href="#" class="btn-primary-cm btn-with-icon">
                                    <i class="mdi mdi-account-circle-outline"></i>
                                    تکمیل حساب کاربری
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <!-- End main-content -->
        <!-- Start mini-footer -->
        <footer class="mini-footer dt-sl">
            <div class="container main-container">
                <div class="row">
                    <div class="col-12">
                        <ul class="mini-footer-menu">
                            <li><a href="#">درباره دیدیکالا</a></li>
                            <li><a href="#">فرصت های شغلی</a></li>
                            <li><a href="#">تماس با ما</a></li>
                            <li><a href="#">همکاری با سازمان ها</a></li>
                        </ul>
                    </div>
                    <div class="col-12 mt-2 mb-3">
                        <div class="footer-light-text">
                            استفاده از مطالب فروشگاه اینترنتی دیدیکالا فقط برای مقاصد غیرتجاری و با ذکر منبع بلامانع
                            است. کلیه حقوق این سایت متعلق به (فروشگاه آنلاین دیدیکالا) می‌باشد.
                        </div>
                    </div>
                    <div class="col-12 text-center">
                        <div class="copy-right-mini-footer">
                            Copyright © 2019 Didikala
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- End mini-footer -->
    </div>
    <!-- colorPanel -->
    <div id="colorswitch-option">
        <button><i class="mdi mdi-settings"></i></button>
        <ul>
            <li class="active" data-path="./assets/css/colors/default.css"><span
                    style="background-color: #f7858d;"></span></li>
            <li data-path="./assets/css/colors/amber-color.css"><span style="background-color: #ffab00;"></span></li>
            <li data-path="./assets/css/colors/blue-color.css"><span style="background-color: #2979ff;"></span></li>
            <li data-path="./assets/css/colors/blue-grey-color.css"><span style="background-color: #607d8b;"></span>
            </li>
            <li data-path="./assets/css/colors/brown-color.css"><span style="background-color: #795548;"></span></li>
            <li data-path="./assets/css/colors/cyan-color.css"><span style="background-color: #00bcd4;"></span></li>
            <li data-path="./assets/css/colors/green-color.css"><span style="background-color: #4caf50;"></span></li>
            <li data-path="./assets/css/colors/indigo-color.css"><span style="background-color: #3f51b5;"></span></li>
            <li data-path="./assets/css/colors/lime-color.css"><span style="background-color: #cddc39;"></span></li>
            <li data-path="./assets/css/colors/orange-color.css"><span style="background-color: #ff9800;"></span></li>
            <li data-path="./assets/css/colors/red-color.css"><span style="background-color: #f44336;"></span></li>
            <li data-path="./assets/css/colors/teal-color.css"><span style="background-color: #009688;"></span></li>
            <li data-path="./assets/css/colors/purple-color.css"><span style="background-color: #9c27b0;"></span></li>
        </ul>
    </div>
    <!-- end colorPanel -->
    <!-- Core JS Files -->
    <script src="./assets/js/vendor/jquery-3.4.1.min.js"></script>
    <script src="./assets/js/vendor/popper.min.js"></script>
    <script src="./assets/js/vendor/bootstrap.min.js"></script>
    <!-- Plugins -->
    <script src="./assets/js/vendor/bootstrap-slider.min.js"></script>
    <script src="./assets/js/vendor/owl.carousel.min.js"></script>
    <script src="./assets/js/vendor/owl.carousel2.thumbs.min.js"></script>
    <script src="./assets/js/vendor/jquery.nicescroll.min.js"></script>
    <script src="./assets/js/vendor/jquery.nice-select.min.js"></script>
    <script src="./assets/js/vendor/nouislider.min.js"></script>
    <script src="./assets/js/vendor/jquery.horizontalmenu.js"></script>
    <script src="./assets/js/vendor/jquery.fancybox.min.js"></script>
    <script src="./assets/js/vendor/countdown.min.js"></script>
    <script src="./assets/js/vendor/wNumb.js"></script>
    <script src="./assets/js/vendor/ResizeSensor.min.js"></script>
    <script src="./assets/js/vendor/theia-sticky-sidebar.min.js"></script>
    <!-- Main JS File -->
    <script src="./assets/js/main.js"></script>
</body>

</html>